### ISSUE TITLE
UITreeView widget

### ISSUE THREAD

**Issue by rzats** [rzats/gsoc-nui-editor#1]
A widget implementing a Tree View - a common visual representation of an informational hierarchy - as a NUI CoreWidget override.
### TODO
- [x] In-memory tree data structure (see: [JavaFX TreeItem](https://docs.oracle.com/javafx/2/api/javafx/scene/control/TreeItem.html), [Swing TreeModel](https://docs.oracle.com/javase/7/docs/api/javax/swing/tree/TreeModel.html))
- [x] Initial TreeView class
- [x] Node addition
- [x] Node deletion
- [x] Node movement
- [x] Node copying & pasting
- [x] InteractionListener overrides for node interactivity
- [x] Save expanded state for nodes
- [x] Readonly flag
- [x] Testing and documentation

**Comment by rzats** [comment]
Closing as finished! See https://github.com/MovingBlocks/Terasology/pull/2338.
