### ISSUE TITLE
NUI Editor

### ISSUE THREAD

**Issue by rzats** [rzats/gsoc-nui-editor#12]
#### Pre-Midterm
- [x] [UITreeView widget (#1)](https://github.com/rzats/gsoc-nui-editor/issues/1)
- [x] [JSON/UITreeView adapter (#2)](https://github.com/rzats/gsoc-nui-editor/issues/2)
- [x] [Core editor interface definitions (#3)](https://github.com/rzats/gsoc-nui-editor/issues/3)
- [x] [Canvas & file selection implementation (#4)](https://github.com/rzats/gsoc-nui-editor/issues/4)
#### Post-Midterm
- [x] [Widget addition, movement, copying and deletion (#5)](https://github.com/rzats/gsoc-nui-editor/issues/5)
- [x] [Inline property editor (#6)](https://github.com/rzats/gsoc-nui-editor/issues/6)
- [x] [Widget icon support (#7)](https://github.com/rzats/gsoc-nui-editor/issues/7)
- [x] [Smart property addition (#8)](https://github.com/rzats/gsoc-nui-editor/issues/8)
- [x] [Interface skin editor (#9)](https://github.com/rzats/gsoc-nui-editor/issues/9)
- [x] [Advanced editor preferences and file saving (#10)](https://github.com/rzats/gsoc-nui-editor/issues/10)
- [x] [Wrap-up and release (#11)](https://github.com/rzats/gsoc-nui-editor/issues/11)
