### ISSUE TITLE
JSON/UITreeView adapter

### ISSUE THREAD

**Issue by rzats** [rzats/gsoc-nui-editor#2]
Binding the UITreeView to a JSON file.
### TODO
- [x] Generate a UITreeView based on a JSON file
- [x] Generate a JSON file based on the state of a UITreeView
- [x] Testing and documentation
