### ISSUE TITLE
Core editor interface definitions

### ISSUE THREAD

**Issue by rzats** [rzats/gsoc-nui-editor#3]
NUI-based interface definition files (*.ui and *.skin assets) to be used by the editor.
### TODO
- [x] Button bindings and command line options to activate the NUI editor
- [x] Control element to hide the active NUI editor
- [x] Interface file selection menu
- [x] JSON tree view window
- [x] ~~Make the window free-floating~~ _Replaced by a static sidebar_
- [x] Editor preferences menu
- [x] Copy Interface button
