### ISSUE TITLE
Canvas & file selection implementation

### ISSUE THREAD

**Issue by rzats** [rzats/gsoc-nui-editor#4]
### TODO
- [x] Populate the interface file selection menu (see #3) by a generated list of asset files.
- [x] Display the screen being edited
- [x] Resolve initialisation oddities
- [x] Reload when edited
