### ISSUE TITLE
Widget addition, movement, copying and deletion

### ISSUE THREAD

**Issue by rzats** [rzats/gsoc-nui-editor#5]
### TODO
- [x] "Add Widget" entries for node context menus
- [x] Move widgets within the hierarchy
- [x] Copy&paste widgets
- [x] Delete widgets

**Comment by flo** [comment]
Movement is implemented? I tried moving an item via drag and drop and it did not work.

**Comment by rzats** [comment]
@flo: what I meant is child position changes within the parent node (UP/DOWN), but drag&drop can be implemented within the `UITreeView` as well :)
Though one problem is that it will only work for two elements displayed on the screen - since `UITreeView` doesn't know about the `ScrollableArea` it's in it won't be able to, for instance, scroll down if an element is dragged to the bottom of the screen (as is the case in IDEA).

**Comment by flo** [comment]
@rzats I think that would be acceptable for now if it doesn't scroll automatically. I guess you would still be able to use the mouse wheel for scrolling while dragging.
