### ISSUE TITLE
Inline property editor

### ISSUE THREAD

**Issue by rzats** [rzats/gsoc-nui-editor#6]
A further update to the core UITreeView widget (see #1).
### TODO
- [x] Make leaf nodes editable when selected (inline UITextEntry)
- [x] Type validation for entered values
- [x] Update asset file when value is changed
