### ISSUE TITLE
Widget icon support

### ISSUE THREAD

**Issue by rzats** [rzats/gsoc-nui-editor#7]
Yet another update to the core UITreeView widget (see #1).
### TODO
- [x] Asset hooks for widget icons
- [x] Icon lookup and rendering
- [x] Create icons for common properties
- [x] Option to disable icons
