### ISSUE TITLE
Smart property addition

### ISSUE THREAD

**Issue by rzats** [rzats/gsoc-nui-editor#8]
Property addition context menu with dynamically generated custom options.
### TODO
- [x] Determine how to obtain JSON value list from a class (annotations?)
- [x] Add properties to context menu
- [x] Autogenerate properties in asset file
- [x] Finish TODO stuff in related Terasology PR
