### ISSUE TITLE
Interface skin editor

### ISSUE THREAD

**Issue by rzats** [rzats/gsoc-nui-editor#9]
A skin editor tree view similar to the interface editor tree view.
### TODO
- [x] Create modified interface definitions (see #3)
- [x] Update widget icons (see #7)
- [x] Update smart property addition (see #8)
